name: Build APICON 2020 Partners APP

on: [push, pull_request]

jobs:
  build-partners-app:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'partners'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker image (latest)
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: cwiechmann/apicon-2020-partners-app
        workdir: ${{env.workingDirectory}}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"